spring:
  application:
    name: crypto-fetcher
  kafka:
    producer:
      bootstrap-servers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

coingecko:
  api:
    url: https://api.coingecko.com/api/v3
    key: ${COINGECKO_API_KEY}

debug: false

crypto:
  price-updater:
    interval: 3600000 # 1h
  data-fetcher:
    interval: 3600000 # 1h

logging:
  level:
    root: INFO
    com.xavelo.crypto.fetcher.infrastructure.in.cron: DEBUG
    com.xavelo.crypto.fetcher.infrastructure.out.external.CoinGeckoApiAdapter: DEBUG