apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-fetcher-deployment
  annotations:
    commitID: "8ec199c82e866cfc7908971c23c7ef7c186d452d"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-fetcher
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-fetcher
    spec:
      containers:
        - name: crypto-fetcher
          image: 'xavelo/crypto-fetcher:8ec199c82e866cfc7908971c23c7ef7c186d452d'
          ports:
            - containerPort: 80
