apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-fetcher-deployment
  annotations:
    commitID: "1e5e879083ed33a851ecd1825e0e0ce7fd65b894"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crypto-fetcher
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-fetcher
    spec:
      containers:
        - name: crypto-fetcher
          image: 'xavelo/crypto-fetcher:1e5e879083ed33a851ecd1825e0e0ce7fd65b894'
          ports:
            - containerPort: 80
