apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-kafka-producer-deployment
  annotations:
    commitID: "ea23b777736fe248943c21679f3314097fbd68cf"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-kafka-producer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-kafka-producer
    spec:
      containers:
        - name: api-kafka-producer
          image: 'xavelo/crypto-fetcher:ea23b777736fe248943c21679f3314097fbd68cf'
          ports:
            - containerPort: 80
