apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-fetcher-deployment
  annotations:
    commitID: "f89e0a2daf34cc2747895e589b01f3cccffddd5e"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-fetcher
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-fetcher
    spec:
      containers:
        - name: api-kafka-producer
          image: 'xavelo/crypto-fetcher:f89e0a2daf34cc2747895e589b01f3cccffddd5e'
          ports:
            - containerPort: 80
