apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-fetcher-deployment
  annotations:
    commitID: "45e43511a7e287b3c53c9ad91c0dbf71fc2ba3c2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-fetcher
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-fetcher
    spec:
      containers:
        - name: api-kafka-producer
          image: 'xavelo/crypto-fetcher:45e43511a7e287b3c53c9ad91c0dbf71fc2ba3c2'
          ports:
            - containerPort: 80
