apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-fetcher-deployment
  annotations:
    commitID: "c2bc01ddfaf31f5b96bc834da33e826a75acdcf3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crypto-fetcher
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-fetcher
    spec:
      containers:
        - name: crypto-fetcher
          image: 'xavelo/crypto-fetcher:c2bc01ddfaf31f5b96bc834da33e826a75acdcf3'
          env:
            - name: COINGECKO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: coingecko-api-secret
                  key: apiKey
          ports:
            - containerPort: 80
