apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-fetcher-deployment
  annotations:
    commitID: "8f30bc37a25e74ff94637536a1e94b9d239a6b54"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-fetcher
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-fetcher
    spec:
      containers:
        - name: crypto-fetcher
          image: 'xavelo/crypto-fetcher:8f30bc37a25e74ff94637536a1e94b9d239a6b54'
          ports:
            - containerPort: 80
