apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: crypto-fetcher
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crypto-fetcher-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 99