apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-fetcher-deployment
  annotations:
    commitID: "d2a1daa5138e5fd07d3813891326acb00c82a446"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-fetcher
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-fetcher
    spec:
      containers:
        - name: api-kafka-producer
          image: 'xavelo/crypto-fetcher:d2a1daa5138e5fd07d3813891326acb00c82a446'
          ports:
            - containerPort: 80
