apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-fetcher-deployment
  annotations:
    commitID: "a6a9deca0ea398b1823584568291cc1767e001ba"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-fetcher
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-fetcher
    spec:
      containers:
        - name: api-kafka-producer
          image: 'xavelo/crypto-fetcher:a6a9deca0ea398b1823584568291cc1767e001ba'
          ports:
            - containerPort: 80
