apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-fetcher-deployment
  annotations:
    commitID: "23f4e1b34496ca3fd497794c44c1577a7f2ca5c9"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-fetcher
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-fetcher
    spec:
      containers:
        - name: crypto-fetcher
          image: 'xavelo/crypto-fetcher:23f4e1b34496ca3fd497794c44c1577a7f2ca5c9'
          ports:
            - containerPort: 80
