apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-fetcher-deployment
  annotations:
    commitID: "c98eaee162b6b94e8e3c0d237edfe469394df69e"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-fetcher
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-fetcher
    spec:
      containers:
        - name: api-kafka-producer
          image: 'xavelo/crypto-fetcher:c98eaee162b6b94e8e3c0d237edfe469394df69e'
          ports:
            - containerPort: 80
