apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-fetcher-deployment
  annotations:
    commitID: "ea3af032bc696e26cd59dc3d89fe5dfae5fa5923"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-fetcher
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-fetcher
    spec:
      containers:
        - name: crypto-fetcher
          image: 'xavelo/crypto-fetcher:ea3af032bc696e26cd59dc3d89fe5dfae5fa5923'
          ports:
            - containerPort: 80
